In [ ]:
# Data Preprocessing
# Partie 1 : Introduction + Exploration + Valeurs manquantes + Doublons

In [ ]:
# ---------------------------
# Chargement et exploration des données
# ---------------------------


import pandas as pd
import numpy as np


# Charger les données à partir d'un fichier csv
df0 = pd.read_csv("donnees_etudiants.csv", sep = ',' , header = 0, index_col = 0);
df0

#Il n'ya pas de references car index col = 0
#Dans mon cas, je souhaite avoir le nom comme une colonne independante donc j'enleve le index-col = 0

          Age Genre  Note
Nom
Alice    25.0     F  85.0
Bob      30.0     M  90.0
Charlie   NaN     M  88.0
Alice    25.0     F  85.0
David    22.0     M   NaN
Emma     27.0     F  78.0

In [ ]:
# Charger les données à partir d'un fichier csv
df = pd.read_csv("donnees_etudiants.csv", sep = ',' , header = 0);
df

       Nom   Age Genre  Note
0    Alice  25.0     F  85.0
1      Bob  30.0     M  90.0
2  Charlie   NaN     M  88.0
3    Alice  25.0     F  85.0
4    David  22.0     M   NaN
5     Emma  27.0     F  78.0

In [ ]:
#Afficher les 5 premieres lignes
df.head()

       Nom   Age Genre  Note
0    Alice  25.0     F  85.0
1      Bob  30.0     M  90.0
2  Charlie   NaN     M  88.0
3    Alice  25.0     F  85.0
4    David  22.0     M   NaN

In [ ]:
#Afficher les 5 dernieres lignes
df.tail()

       Nom   Age Genre  Note
1      Bob  30.0     M  90.0
2  Charlie   NaN     M  88.0
3    Alice  25.0     F  85.0
4    David  22.0     M   NaN
5     Emma  27.0     F  78.0

In [ ]:
#Enumerer les colonnes
df.columns

Index(['Nom', 'Age', 'Genre', 'Note'], dtype='object')

In [ ]:
#Indiquer le type de chaque colonnes
df.dtypes

Nom       object
Age      float64
Genre     object
Note     float64
dtype: object

In [ ]:
#Faites un resume statistiques de toutes les variables dans df

df.describe()

             Age       Note
count   5.000000   5.000000
mean   25.800000  85.200000
std     2.949576   4.549725
min    22.000000  78.000000
25%    25.000000  85.000000
50%    25.000000  85.000000
75%    27.000000  88.000000
max    30.000000  90.000000

In [ ]:
#Resume statistique seulement de la variable Note

df['Note'].describe()

count     5.000000
mean     85.200000
std       4.549725
min      78.000000
25%      85.000000
50%      85.000000
75%      88.000000
max      90.000000
Name: Note, dtype: float64

In [ ]:
# Informations générales
# Infos sur les types de données et les valeurs manquantes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nom     6 non-null      object
 1   Age     5 non-null      float64
 2   Genre   6 non-null      object
 3   Note    5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [ ]:
# ---------------------------
# 3. Traitement des valeurs manquantes
# ---------------------------

# Identifier les valeurs manquantes
print("\nNombre de valeurs manquantes par colonne :")
print(df.isnull().sum())

Nombre de valeurs manquantes par colonne :
Nom      0
Age      1
Genre    0
Note     1
dtype: int64

In [ ]:
# Exemple 1 : Suppression des lignes avec des valeurs manquantes
df_dropna = df.dropna()
print("\nDonnées après suppression des lignes avec valeurs manquantes :")
print(df_dropna)

Données après suppression des lignes avec valeurs manquantes :
     Nom   Age Genre  Note
0  Alice  25.0     F  85.0
1    Bob  30.0     M  90.0
3  Alice  25.0     F  85.0
5   Emma  27.0     F  78.0

In [ ]:
#Example 1.1 - Supprimer les valeurs manquantes pour la variable Genre
#df = df.dropna(subset=['Genre'])

In [ ]:
# Exemple 2 : Remplissage des valeurs manquantes

# Remplir la note manquante par 0 (exemple simple)
df["Note"] = df["Note"].fillna(0)

#OU BIEN
# Remplir l'âge manquant par la moyenne
moyenne_age = df["Age"].mean()
df["Age"] = df["Age"].fillna(moyenne_age)

df

       Nom   Age Genre  Note
0    Alice  25.0     F  85.0
1      Bob  30.0     M  90.0
2  Charlie  25.8     M  88.0
3    Alice  25.0     F  85.0
4    David  22.0     M   0.0
5     Emma  27.0     F  78.0

In [ ]:
# 4. Détection et suppression des doublons
# ---------------------------

print("\nVérification de doublons :")
print(df.duplicated())

print("\nNombre de doublons :", df.duplicated().sum())

Vérification de doublons :
0    False
1    False
2    False
3     True
4    False
5    False
dtype: bool

Nombre de doublons : 1

In [ ]:
# Supprimer les doublons

Données après suppression des doublons :
       Nom   Age Genre  Note
0    Alice  25.0     F  85.0
1      Bob  30.0     M  90.0
2  Charlie  25.8     M  88.0
4    David  22.0     M   0.0
5     Emma  27.0     F  78.0

In [ ]:
#Nous pouvons meme decider si je laisse le premier ou le deuxieme
df2 = df.drop_duplicates(subset=None, keep='first', inplace=False)

#keep='first'	 Par défaut – garde la 1ère occurrence
#keep='last'	garde la dernière
#keep=False	supprime toutes les occurrences dupliquées

#print(df.drop_duplicates())  # équivalent à keep='first'

#subset=None
#Cela veut dire que toutes les colonnes seront utilisées pour déterminer si deux lignes sont identiques.

In [ ]:
#df.drop_duplicates(subset='Nomdelacolonne1')
#df.drop_duplicates(subset=['Nomdelacolonne1', 'Nomdelacolonne2'])

#Supprime les doublons basés uniquement sur la colonne 'val', même si les autres colonnes sont différentes.

In [ ]:
#False (défaut)	renvoie un nouveau DataFrame sans doublons
#True	: modifie directement le DataFrame existant (aucun retour)

#Par d2faut si on ne mets rien comme dans notre cas donc c'est false
#envoie un nouveau dataFrame nettoye

#En fait df.drop_duplicates() c'est equivqlent a
#df.drop_duplicates(subset=None, keep='first', inplace=False)
#C'est pour cela on appelle le nom d'un nouveau dataframe = df.drop_duplicates()