# Learning Objectives

Understand the dataset, 
Data preprocessing - Cleaning and Cleansing and 
Data analysis

# Data importation

In [64]:
import seaborn as sns
import pandas as pd
import numpy as np
import random

In [65]:
# 1. Load the Dataset Titanic built-in in python
df = sns.load_dataset("titanic")

In [66]:
# 2. get the size of the dataset
df.shape

(891, 15)

In [67]:
#Show the first 5 rows
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [68]:
#Show the last 5 rows
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [69]:
# get the info of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

# Data Preprocessing

In [98]:
#check missing values
df.isna().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [153]:
# manage missing values as you see pertinent
age_moy = df["age"].mean()
age_moye = int(age_moy)
df["age"] = df["age"].fillna(age_moye)

In [154]:
#check missing values
df.isna().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [155]:
# manage missing values as you see pertinent

df['embarked'] = df['embarked'].fillna('S')
df.isna().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [195]:
# manage missing values as you see pertinent
# manage missing values as you see pertinent
df = df.drop(columns = ['deck'])
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,Southampton,no,True
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,Southampton,yes,True
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,Southampton,no,False
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,Queenstown,no,True

In [157]:
#check missing values
df['embark_town'] = df['embark_town'].fillna('Southampton')

df.isna().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [158]:
# Check for duplicate rows
print(df.duplicated())
print("\nNombre de doublons :", df.duplicated().sum())

0      False
1      False
2      False
3      False
4      False
       ...
886     True
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

Nombre de doublons : 107

In [159]:
#Drop duplicates keeping the first occurance
df_final = df.drop_duplicates(keep='first')
print("\nDonnées après suppression des doublons :")
print(df_final)

Données après suppression des doublons :
     survived  pclass     sex        age  sibsp  parch     fare embarked  \
0           0       3    male  22.000000      1      0   7.2500        S
1           1       1  female  38.000000      1      0  71.2833        C
2           1       3  female  26.000000      0      0   7.9250        S
3           1       1  female  35.000000      1      0  53.1000        S
4           0       3    male  35.000000      0      0   8.0500        S
..        ...     ...     ...        ...    ...    ...      ...      ...
885         0       3  female  39.000000      0      5  29.1250        Q
887         1       1  female  19.000000      0      0  30.0000        S
888         0       3  female  29.699118      1      2  23.4500        S
889         1       1    male  26.000000      0      0  30.0000        C
890         0       3    male  32.000000      0      0   7.7500        Q

     class    who  adult_male deck  embark_town alive  alone
0    Third    man        True    A  Southampton    no  False
1    First  woman       False    C    Cherbourg   yes  False
2    Third  woman       False    A  Southampton   yes   True
3    First  woman       False    C  Southampton   yes  False
4    Third    man        True    A  Southampton    no   True
..     ...    ...         ...  ...          ...   ...    ...
885  Third  woman       False    A   Queenstown    no  False
887  First  woman       False    B  Southampton   yes   True
888  Third  woman       False    A  Southampton    no  False
889  First    man        True    C    Cherbourg   yes   True
890  Third    man        True    A   Queenstown    no   True

[784 rows x 15 columns]

In [160]:
# Check for duplicate rows
print(df_final.duplicated())
print("\nNombre de doublons :", df_final.duplicated().sum())

0      False
1      False
2      False
3      False
4      False
       ...
885    False
887    False
888    False
889    False
890    False
Length: 784, dtype: bool

Nombre de doublons : 0

In [161]:
#show the final dataset 5 first rows

df_final.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,A,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,A,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,A,Southampton,no,True

1. Which columns are numerical? Which are categorical?

# Data Analysis

In [162]:
#Is there more people alive or dead ? Intepret in %
p_alive = df_final['alive'].value_counts(normalize=True) * 100
p_alive
# Il y a plus de personne décédées que de vivant: 58 pourcent de mort contre 41 pourcent de vivant

alive
no     58.80102
yes    41.19898
Name: proportion, dtype: float64

In [163]:
#group survival status (alive) by embarkation town (embark_town) and calculate both counts and percentages.
group = df_final.groupby('embark_town')['alive'].value_counts()
group

embark_town  alive
Cherbourg    yes       90
             no        65
Queenstown   no        39
             yes       20
Southampton  no       357
             yes      213
Name: count, dtype: int64

In [164]:
#The question but in %

group = df_final.groupby('embark_town')['alive'].value_counts(normalize = True)*100
group

embark_town  alive
Cherbourg    yes      58.064516
             no       41.935484
Queenstown   no       66.101695
             yes      33.898305
Southampton  no       62.631579
             yes      37.368421
Name: proportion, dtype: float64

In [181]:
#How many classes do we have ?

df_final['pclass'].nunique()

3

In [182]:
#Enumerate the different classes
df_final['pclass'].unique()

array([3, 1, 2])

In [183]:
#Is there more man or women embarked in the Titanic. Count the number of men and number of women
sex = df_final['sex'].value_counts()
sex
# Il ya plus d'homme

sex
male      491
female    293
Name: count, dtype: int64

In [184]:
#analyse your results in %


sex = df_final['sex'].value_counts(normalize =True)*100
sex

sex
male      62.627551
female    37.372449
Name: proportion, dtype: float64

In [185]:
#What is the maximum age and the minimum age of people embarked ? 
print(df_final['age'].min())
print(df_final['age'].max())

0.42
80.0

In [186]:
#What is the maximum age and the minimum age of people embarked ?
#min

In [187]:
#max

In [191]:
#What is the average age ?
print(df_final['age'].mean(),'ans')

29.846334783913566 ans

In [178]:
#How many embark_town are they ?

df['embark_town'].nunique()

3

In [179]:
##List the embarked towns

#How many embark_town are they ?

df['embark_town'].unique()

array(['Southampton', 'Cherbourg', 'Queenstown'], dtype=object)

### Indexing

### Using .loc[] (Label-based indexing)

In [31]:
#Select all information about the passenger at index 0.

In [32]:
#Select all information about the passenger at index 50.

In [33]:
#Get the sex and age of the passenger at index 10.

In [34]:
#Select passengers from index 100 to 105 and show only their survived and pclass columns.

In [35]:
#Get all passengers who embarked from "Southampton" and display only sex, age, and fare

In [36]:
#Select the first 5 female passengers and display their age, pclass, and survived.

### Using .iloc[] (Position-based indexing)

In [37]:
#Display the first row of the dataset.

In [38]:
#Get the values of age and fare for the 5th passenger (row index 4).

In [39]:
#Display the first 10 passengers (rows 0–9) but only the first 3 columns (survived, pclass, sex).